services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./src/orders-api:/var/www
    depends_on:
      - db
    networks:
      - private
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "9005:9005"
    volumes:
      - ./src/orders-api:/var/www
    depends_on:
      - db
    networks:
      - private
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ordersdb
      - MYSQL_ROOT_PASSWORD=orderspassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=orderspassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private
      
networks:
  private:

volumes:
  db_data: